#!bin/bash
module load kraken2/2.0.8
cd /home/labs/straussman/tatianas/rna-seq/join_both_cohorts/
# First, generate the kraken2 command line for each file
#for f in `ls *.fastq | sed 's/_unmapped_reads_R[12].fastq//g' | sed 's/STAR_//g' | sort -u`;
#do
#echo "bsub  -q  new-short  -J  kraken_$f -R  rusage[mem=64000]  -e kraken_$f.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_${f}_unmapped_reads.kreport --paired STAR_${f}_unmapped_reads_R1.fastq STAR_${f}_unmapped_reads_R2.fastq --output kraken_$f.o  --report-zero-counts  --confidence  0.1"
#done


#after this step is done, don't forget to remove the extra space before_1 and_2 file names, and to remove the incorrect inserted path to .o and .e files (I am not sure how to prevent this two wrong behaviors, but correcting it is very fast...) ;-)

# Now run all the jobs for step 5 that you need, in parallel:
bsub  -q  new-short  -J  kraken_0142-20-NHR-13 -R  rusage[mem=64000]  -e kraken_0142-20-NHR-13.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_0142-20-NHR-13_unmapped_reads.kreport --paired STAR_0142-20-NHR-13_unmapped_reads_R1.fastq STAR_0142-20-NHR-13_unmapped_reads_R2.fastq --output kraken_0142-20-NHR-13.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_0142-20-NHR-14 -R  rusage[mem=64000]  -e kraken_0142-20-NHR-14.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_0142-20-NHR-14_unmapped_reads.kreport --paired STAR_0142-20-NHR-14_unmapped_reads_R1.fastq STAR_0142-20-NHR-14_unmapped_reads_R2.fastq --output kraken_0142-20-NHR-14.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_0142-20-NHR-15 -R  rusage[mem=64000]  -e kraken_0142-20-NHR-15.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_0142-20-NHR-15_unmapped_reads.kreport --paired STAR_0142-20-NHR-15_unmapped_reads_R1.fastq STAR_0142-20-NHR-15_unmapped_reads_R2.fastq --output kraken_0142-20-NHR-15.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_0142-20-NHR-16 -R  rusage[mem=64000]  -e kraken_0142-20-NHR-16.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_0142-20-NHR-16_unmapped_reads.kreport --paired STAR_0142-20-NHR-16_unmapped_reads_R1.fastq STAR_0142-20-NHR-16_unmapped_reads_R2.fastq --output kraken_0142-20-NHR-16.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_0142-20-NHR-17 -R  rusage[mem=64000]  -e kraken_0142-20-NHR-17.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_0142-20-NHR-17_unmapped_reads.kreport --paired STAR_0142-20-NHR-17_unmapped_reads_R1.fastq STAR_0142-20-NHR-17_unmapped_reads_R2.fastq --output kraken_0142-20-NHR-17.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_0142-20-NHR-18 -R  rusage[mem=64000]  -e kraken_0142-20-NHR-18.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_0142-20-NHR-18_unmapped_reads.kreport --paired STAR_0142-20-NHR-18_unmapped_reads_R1.fastq STAR_0142-20-NHR-18_unmapped_reads_R2.fastq --output kraken_0142-20-NHR-18.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_0142-20-NHR-19 -R  rusage[mem=64000]  -e kraken_0142-20-NHR-19.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_0142-20-NHR-19_unmapped_reads.kreport --paired STAR_0142-20-NHR-19_unmapped_reads_R1.fastq STAR_0142-20-NHR-19_unmapped_reads_R2.fastq --output kraken_0142-20-NHR-19.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_H002 -R  rusage[mem=64000]  -e kraken_H002.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_H002_unmapped_reads.kreport --paired STAR_H002_unmapped_reads_R1.fastq STAR_H002_unmapped_reads_R2.fastq --output kraken_H002.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_H005 -R  rusage[mem=64000]  -e kraken_H005.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_H005_unmapped_reads.kreport --paired STAR_H005_unmapped_reads_R1.fastq STAR_H005_unmapped_reads_R2.fastq --output kraken_H005.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_H007 -R  rusage[mem=64000]  -e kraken_H007.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_H007_unmapped_reads.kreport --paired STAR_H007_unmapped_reads_R1.fastq STAR_H007_unmapped_reads_R2.fastq --output kraken_H007.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_H013 -R  rusage[mem=64000]  -e kraken_H013.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_H013_unmapped_reads.kreport --paired STAR_H013_unmapped_reads_R1.fastq STAR_H013_unmapped_reads_R2.fastq --output kraken_H013.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_H015 -R  rusage[mem=64000]  -e kraken_H015.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_H015_unmapped_reads.kreport --paired STAR_H015_unmapped_reads_R1.fastq STAR_H015_unmapped_reads_R2.fastq --output kraken_H015.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_H021 -R  rusage[mem=64000]  -e kraken_H021.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_H021_unmapped_reads.kreport --paired STAR_H021_unmapped_reads_R1.fastq STAR_H021_unmapped_reads_R2.fastq --output kraken_H021.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_H022 -R  rusage[mem=64000]  -e kraken_H022.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_H022_unmapped_reads.kreport --paired STAR_H022_unmapped_reads_R1.fastq STAR_H022_unmapped_reads_R2.fastq --output kraken_H022.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_H023 -R  rusage[mem=64000]  -e kraken_H023.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_H023_unmapped_reads.kreport --paired STAR_H023_unmapped_reads_R1.fastq STAR_H023_unmapped_reads_R2.fastq --output kraken_H023.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL11 -R  rusage[mem=64000]  -e kraken_ICL11.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL11_unmapped_reads.kreport --paired STAR_ICL11_unmapped_reads_R1.fastq STAR_ICL11_unmapped_reads_R2.fastq --output kraken_ICL11.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL2 -R  rusage[mem=64000]  -e kraken_ICL2.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL2_unmapped_reads.kreport --paired STAR_ICL2_unmapped_reads_R1.fastq STAR_ICL2_unmapped_reads_R2.fastq --output kraken_ICL2.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL20 -R  rusage[mem=64000]  -e kraken_ICL20.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL20_unmapped_reads.kreport --paired STAR_ICL20_unmapped_reads_R1.fastq STAR_ICL20_unmapped_reads_R2.fastq --output kraken_ICL20.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL22 -R  rusage[mem=64000]  -e kraken_ICL22.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL22_unmapped_reads.kreport --paired STAR_ICL22_unmapped_reads_R1.fastq STAR_ICL22_unmapped_reads_R2.fastq --output kraken_ICL22.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL24 -R  rusage[mem=64000]  -e kraken_ICL24.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL24_unmapped_reads.kreport --paired STAR_ICL24_unmapped_reads_R1.fastq STAR_ICL24_unmapped_reads_R2.fastq --output kraken_ICL24.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL31 -R  rusage[mem=64000]  -e kraken_ICL31.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL31_unmapped_reads.kreport --paired STAR_ICL31_unmapped_reads_R1.fastq STAR_ICL31_unmapped_reads_R2.fastq --output kraken_ICL31.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL34 -R  rusage[mem=64000]  -e kraken_ICL34.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL34_unmapped_reads.kreport --paired STAR_ICL34_unmapped_reads_R1.fastq STAR_ICL34_unmapped_reads_R2.fastq --output kraken_ICL34.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL37 -R  rusage[mem=64000]  -e kraken_ICL37.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL37_unmapped_reads.kreport --paired STAR_ICL37_unmapped_reads_R1.fastq STAR_ICL37_unmapped_reads_R2.fastq --output kraken_ICL37.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL48 -R  rusage[mem=64000]  -e kraken_ICL48.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL48_unmapped_reads.kreport --paired STAR_ICL48_unmapped_reads_R1.fastq STAR_ICL48_unmapped_reads_R2.fastq --output kraken_ICL48.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL5 -R  rusage[mem=64000]  -e kraken_ICL5.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL5_unmapped_reads.kreport --paired STAR_ICL5_unmapped_reads_R1.fastq STAR_ICL5_unmapped_reads_R2.fastq --output kraken_ICL5.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL54 -R  rusage[mem=64000]  -e kraken_ICL54.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL54_unmapped_reads.kreport --paired STAR_ICL54_unmapped_reads_R1.fastq STAR_ICL54_unmapped_reads_R2.fastq --output kraken_ICL54.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL56 -R  rusage[mem=64000]  -e kraken_ICL56.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL56_unmapped_reads.kreport --paired STAR_ICL56_unmapped_reads_R1.fastq STAR_ICL56_unmapped_reads_R2.fastq --output kraken_ICL56.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL59 -R  rusage[mem=64000]  -e kraken_ICL59.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL59_unmapped_reads.kreport --paired STAR_ICL59_unmapped_reads_R1.fastq STAR_ICL59_unmapped_reads_R2.fastq --output kraken_ICL59.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL62 -R  rusage[mem=64000]  -e kraken_ICL62.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL62_unmapped_reads.kreport --paired STAR_ICL62_unmapped_reads_R1.fastq STAR_ICL62_unmapped_reads_R2.fastq --output kraken_ICL62.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL66 -R  rusage[mem=64000]  -e kraken_ICL66.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL66_unmapped_reads.kreport --paired STAR_ICL66_unmapped_reads_R1.fastq STAR_ICL66_unmapped_reads_R2.fastq --output kraken_ICL66.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL69 -R  rusage[mem=64000]  -e kraken_ICL69.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL69_unmapped_reads.kreport --paired STAR_ICL69_unmapped_reads_R1.fastq STAR_ICL69_unmapped_reads_R2.fastq --output kraken_ICL69.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_ICL8 -R  rusage[mem=64000]  -e kraken_ICL8.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_ICL8_unmapped_reads.kreport --paired STAR_ICL8_unmapped_reads_R1.fastq STAR_ICL8_unmapped_reads_R2.fastq --output kraken_ICL8.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_IM_116 -R  rusage[mem=64000]  -e kraken_IM_116.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_IM_116_unmapped_reads.kreport --paired STAR_IM_116_unmapped_reads_R1.fastq STAR_IM_116_unmapped_reads_R2.fastq --output kraken_IM_116.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_IM_119 -R  rusage[mem=64000]  -e kraken_IM_119.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_IM_119_unmapped_reads.kreport --paired STAR_IM_119_unmapped_reads_R1.fastq STAR_IM_119_unmapped_reads_R2.fastq --output kraken_IM_119.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_IM_134 -R  rusage[mem=64000]  -e kraken_IM_134.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_IM_134_unmapped_reads.kreport --paired STAR_IM_134_unmapped_reads_R1.fastq STAR_IM_134_unmapped_reads_R2.fastq --output kraken_IM_134.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-005 -R  rusage[mem=64000]  -e kraken_MB38-005.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-005_unmapped_reads.kreport --paired STAR_MB38-005_unmapped_reads_R1.fastq STAR_MB38-005_unmapped_reads_R2.fastq --output kraken_MB38-005.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-007 -R  rusage[mem=64000]  -e kraken_MB38-007.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-007_unmapped_reads.kreport --paired STAR_MB38-007_unmapped_reads_R1.fastq STAR_MB38-007_unmapped_reads_R2.fastq --output kraken_MB38-007.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-012 -R  rusage[mem=64000]  -e kraken_MB38-012.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-012_unmapped_reads.kreport --paired STAR_MB38-012_unmapped_reads_R1.fastq STAR_MB38-012_unmapped_reads_R2.fastq --output kraken_MB38-012.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-014 -R  rusage[mem=64000]  -e kraken_MB38-014.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-014_unmapped_reads.kreport --paired STAR_MB38-014_unmapped_reads_R1.fastq STAR_MB38-014_unmapped_reads_R2.fastq --output kraken_MB38-014.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-021 -R  rusage[mem=64000]  -e kraken_MB38-021.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-021_unmapped_reads.kreport --paired STAR_MB38-021_unmapped_reads_R1.fastq STAR_MB38-021_unmapped_reads_R2.fastq --output kraken_MB38-021.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-301 -R  rusage[mem=64000]  -e kraken_MB38-301.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-301_unmapped_reads.kreport --paired STAR_MB38-301_unmapped_reads_R1.fastq STAR_MB38-301_unmapped_reads_R2.fastq --output kraken_MB38-301.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-302 -R  rusage[mem=64000]  -e kraken_MB38-302.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-302_unmapped_reads.kreport --paired STAR_MB38-302_unmapped_reads_R1.fastq STAR_MB38-302_unmapped_reads_R2.fastq --output kraken_MB38-302.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-308 -R  rusage[mem=64000]  -e kraken_MB38-308.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-308_unmapped_reads.kreport --paired STAR_MB38-308_unmapped_reads_R1.fastq STAR_MB38-308_unmapped_reads_R2.fastq --output kraken_MB38-308.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-311 -R  rusage[mem=64000]  -e kraken_MB38-311.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-311_unmapped_reads.kreport --paired STAR_MB38-311_unmapped_reads_R1.fastq STAR_MB38-311_unmapped_reads_R2.fastq --output kraken_MB38-311.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-314 -R  rusage[mem=64000]  -e kraken_MB38-314.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-314_unmapped_reads.kreport --paired STAR_MB38-314_unmapped_reads_R1.fastq STAR_MB38-314_unmapped_reads_R2.fastq --output kraken_MB38-314.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-316 -R  rusage[mem=64000]  -e kraken_MB38-316.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-316_unmapped_reads.kreport --paired STAR_MB38-316_unmapped_reads_R1.fastq STAR_MB38-316_unmapped_reads_R2.fastq --output kraken_MB38-316.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-330 -R  rusage[mem=64000]  -e kraken_MB38-330.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-330_unmapped_reads.kreport --paired STAR_MB38-330_unmapped_reads_R1.fastq STAR_MB38-330_unmapped_reads_R2.fastq --output kraken_MB38-330.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_MB38-333 -R  rusage[mem=64000]  -e kraken_MB38-333.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_MB38-333_unmapped_reads.kreport --paired STAR_MB38-333_unmapped_reads_R1.fastq STAR_MB38-333_unmapped_reads_R2.fastq --output kraken_MB38-333.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM11_S13 -R  rusage[mem=64000]  -e kraken_TUM11_S13.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM11_S13_unmapped_reads.kreport --paired STAR_TUM11_S13_unmapped_reads_R1.fastq STAR_TUM11_S13_unmapped_reads_R2.fastq --output kraken_TUM11_S13.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM18_S24 -R  rusage[mem=64000]  -e kraken_TUM18_S24.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM18_S24_unmapped_reads.kreport --paired STAR_TUM18_S24_unmapped_reads_R1.fastq STAR_TUM18_S24_unmapped_reads_R2.fastq --output kraken_TUM18_S24.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM1_S17 -R  rusage[mem=64000]  -e kraken_TUM1_S17.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM1_S17_unmapped_reads.kreport --paired STAR_TUM1_S17_unmapped_reads_R1.fastq STAR_TUM1_S17_unmapped_reads_R2.fastq --output kraken_TUM1_S17.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM33_S35 -R  rusage[mem=64000]  -e kraken_TUM33_S35.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM33_S35_unmapped_reads.kreport --paired STAR_TUM33_S35_unmapped_reads_R1.fastq STAR_TUM33_S35_unmapped_reads_R2.fastq --output kraken_TUM33_S35.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM35_S12 -R  rusage[mem=64000]  -e kraken_TUM35_S12.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM35_S12_unmapped_reads.kreport --paired STAR_TUM35_S12_unmapped_reads_R1.fastq STAR_TUM35_S12_unmapped_reads_R2.fastq --output kraken_TUM35_S12.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM37_S69 -R  rusage[mem=64000]  -e kraken_TUM37_S69.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM37_S69_unmapped_reads.kreport --paired STAR_TUM37_S69_unmapped_reads_R1.fastq STAR_TUM37_S69_unmapped_reads_R2.fastq --output kraken_TUM37_S69.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM38_S23 -R  rusage[mem=64000]  -e kraken_TUM38_S23.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM38_S23_unmapped_reads.kreport --paired STAR_TUM38_S23_unmapped_reads_R1.fastq STAR_TUM38_S23_unmapped_reads_R2.fastq --output kraken_TUM38_S23.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM39_S30 -R  rusage[mem=64000]  -e kraken_TUM39_S30.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM39_S30_unmapped_reads.kreport --paired STAR_TUM39_S30_unmapped_reads_R1.fastq STAR_TUM39_S30_unmapped_reads_R2.fastq --output kraken_TUM39_S30.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM3_S63 -R  rusage[mem=64000]  -e kraken_TUM3_S63.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM3_S63_unmapped_reads.kreport --paired STAR_TUM3_S63_unmapped_reads_R1.fastq STAR_TUM3_S63_unmapped_reads_R2.fastq --output kraken_TUM3_S63.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM40_S45 -R  rusage[mem=64000]  -e kraken_TUM40_S45.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM40_S45_unmapped_reads.kreport --paired STAR_TUM40_S45_unmapped_reads_R1.fastq STAR_TUM40_S45_unmapped_reads_R2.fastq --output kraken_TUM40_S45.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM41_S27 -R  rusage[mem=64000]  -e kraken_TUM41_S27.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM41_S27_unmapped_reads.kreport --paired STAR_TUM41_S27_unmapped_reads_R1.fastq STAR_TUM41_S27_unmapped_reads_R2.fastq --output kraken_TUM41_S27.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM42_S58 -R  rusage[mem=64000]  -e kraken_TUM42_S58.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM42_S58_unmapped_reads.kreport --paired STAR_TUM42_S58_unmapped_reads_R1.fastq STAR_TUM42_S58_unmapped_reads_R2.fastq --output kraken_TUM42_S58.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM43_S64 -R  rusage[mem=64000]  -e kraken_TUM43_S64.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM43_S64_unmapped_reads.kreport --paired STAR_TUM43_S64_unmapped_reads_R1.fastq STAR_TUM43_S64_unmapped_reads_R2.fastq --output kraken_TUM43_S64.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM44_S25 -R  rusage[mem=64000]  -e kraken_TUM44_S25.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM44_S25_unmapped_reads.kreport --paired STAR_TUM44_S25_unmapped_reads_R1.fastq STAR_TUM44_S25_unmapped_reads_R2.fastq --output kraken_TUM44_S25.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM46_S36 -R  rusage[mem=64000]  -e kraken_TUM46_S36.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM46_S36_unmapped_reads.kreport --paired STAR_TUM46_S36_unmapped_reads_R1.fastq STAR_TUM46_S36_unmapped_reads_R2.fastq --output kraken_TUM46_S36.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM47_S19 -R  rusage[mem=64000]  -e kraken_TUM47_S19.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM47_S19_unmapped_reads.kreport --paired STAR_TUM47_S19_unmapped_reads_R1.fastq STAR_TUM47_S19_unmapped_reads_R2.fastq --output kraken_TUM47_S19.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM48_S10 -R  rusage[mem=64000]  -e kraken_TUM48_S10.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM48_S10_unmapped_reads.kreport --paired STAR_TUM48_S10_unmapped_reads_R1.fastq STAR_TUM48_S10_unmapped_reads_R2.fastq --output kraken_TUM48_S10.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM54_S11 -R  rusage[mem=64000]  -e kraken_TUM54_S11.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM54_S11_unmapped_reads.kreport --paired STAR_TUM54_S11_unmapped_reads_R1.fastq STAR_TUM54_S11_unmapped_reads_R2.fastq --output kraken_TUM54_S11.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM55_S15 -R  rusage[mem=64000]  -e kraken_TUM55_S15.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM55_S15_unmapped_reads.kreport --paired STAR_TUM55_S15_unmapped_reads_R1.fastq STAR_TUM55_S15_unmapped_reads_R2.fastq --output kraken_TUM55_S15.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM56_S71 -R  rusage[mem=64000]  -e kraken_TUM56_S71.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM56_S71_unmapped_reads.kreport --paired STAR_TUM56_S71_unmapped_reads_R1.fastq STAR_TUM56_S71_unmapped_reads_R2.fastq --output kraken_TUM56_S71.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM57_S47 -R  rusage[mem=64000]  -e kraken_TUM57_S47.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM57_S47_unmapped_reads.kreport --paired STAR_TUM57_S47_unmapped_reads_R1.fastq STAR_TUM57_S47_unmapped_reads_R2.fastq --output kraken_TUM57_S47.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM58_S66 -R  rusage[mem=64000]  -e kraken_TUM58_S66.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM58_S66_unmapped_reads.kreport --paired STAR_TUM58_S66_unmapped_reads_R1.fastq STAR_TUM58_S66_unmapped_reads_R2.fastq --output kraken_TUM58_S66.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM59_S41 -R  rusage[mem=64000]  -e kraken_TUM59_S41.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM59_S41_unmapped_reads.kreport --paired STAR_TUM59_S41_unmapped_reads_R1.fastq STAR_TUM59_S41_unmapped_reads_R2.fastq --output kraken_TUM59_S41.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM60_S56 -R  rusage[mem=64000]  -e kraken_TUM60_S56.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM60_S56_unmapped_reads.kreport --paired STAR_TUM60_S56_unmapped_reads_R1.fastq STAR_TUM60_S56_unmapped_reads_R2.fastq --output kraken_TUM60_S56.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM61_S43 -R  rusage[mem=64000]  -e kraken_TUM61_S43.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM61_S43_unmapped_reads.kreport --paired STAR_TUM61_S43_unmapped_reads_R1.fastq STAR_TUM61_S43_unmapped_reads_R2.fastq --output kraken_TUM61_S43.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM62_S2 -R  rusage[mem=64000]  -e kraken_TUM62_S2.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM62_S2_unmapped_reads.kreport --paired STAR_TUM62_S2_unmapped_reads_R1.fastq STAR_TUM62_S2_unmapped_reads_R2.fastq --output kraken_TUM62_S2.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM66_S50 -R  rusage[mem=64000]  -e kraken_TUM66_S50.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM66_S50_unmapped_reads.kreport --paired STAR_TUM66_S50_unmapped_reads_R1.fastq STAR_TUM66_S50_unmapped_reads_R2.fastq --output kraken_TUM66_S50.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM67_S62 -R  rusage[mem=64000]  -e kraken_TUM67_S62.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM67_S62_unmapped_reads.kreport --paired STAR_TUM67_S62_unmapped_reads_R1.fastq STAR_TUM67_S62_unmapped_reads_R2.fastq --output kraken_TUM67_S62.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM70_S54 -R  rusage[mem=64000]  -e kraken_TUM70_S54.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM70_S54_unmapped_reads.kreport --paired STAR_TUM70_S54_unmapped_reads_R1.fastq STAR_TUM70_S54_unmapped_reads_R2.fastq --output kraken_TUM70_S54.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM80_S59 -R  rusage[mem=64000]  -e kraken_TUM80_S59.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM80_S59_unmapped_reads.kreport --paired STAR_TUM80_S59_unmapped_reads_R1.fastq STAR_TUM80_S59_unmapped_reads_R2.fastq --output kraken_TUM80_S59.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM82_S55 -R  rusage[mem=64000]  -e kraken_TUM82_S55.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM82_S55_unmapped_reads.kreport --paired STAR_TUM82_S55_unmapped_reads_R1.fastq STAR_TUM82_S55_unmapped_reads_R2.fastq --output kraken_TUM82_S55.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM89_S42 -R  rusage[mem=64000]  -e kraken_TUM89_S42.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM89_S42_unmapped_reads.kreport --paired STAR_TUM89_S42_unmapped_reads_R1.fastq STAR_TUM89_S42_unmapped_reads_R2.fastq --output kraken_TUM89_S42.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM91_S39 -R  rusage[mem=64000]  -e kraken_TUM91_S39.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM91_S39_unmapped_reads.kreport --paired STAR_TUM91_S39_unmapped_reads_R1.fastq STAR_TUM91_S39_unmapped_reads_R2.fastq --output kraken_TUM91_S39.o  --report-zero-counts  --confidence  0.1
bsub  -q  new-short  -J  kraken_TUM96_S6 -R  rusage[mem=64000]  -e kraken_TUM96_S6.e  kraken2  --db  /home/labs/straussman/tatianas/kraken_plusPF_database/  --threads  36  --report kraken_TUM96_S6_unmapped_reads.kreport --paired STAR_TUM96_S6_unmapped_reads_R1.fastq STAR_TUM96_S6_unmapped_reads_R2.fastq --output kraken_TUM96_S6.o  --report-zero-counts  --confidence  0.1
